# Generated by Django 3.2.5 on 2021-09-30 19:10

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageLink', models.CharField(max_length=1000)),
                ('ImageTitle', models.CharField(max_length=50)),
                ('ImageDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('news_slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True)),
            ],
        ),
    ]
