# Generated by Django 3.2.5 on 2021-10-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0002_alter_passenger_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='middleName',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
