# Generated by Django 3.2.5 on 2021-10-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0003_alter_passenger_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='flight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='flight_app.flight'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='passenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='flight_app.passenger'),
        ),
    ]
