s1 = {"apk","bat","bin","cgi","com","exe","jar","py","wsf","aif","cda","iff","mid ","midi","mp3","mpa","wav","wma","wpl","avi","flv","h264","m4v","mkv","mov","mp4","mpg ","mpeg","rm","swf","vob","wmv","3g2","3gp","doc ","docx","odt","msg","pdf","rtf","tex","txt","wks ","wps","wpd","ods","xlr","xls","xlsx","key","odp","pps","ppt","pptx","accdb","csv","dat","db ","dbf","log","mdb","pdb","sav","sql","tar","bak","cab","cfg","cpl","cur","dll","dmp","drv","icns","ico","ini","lnk","msi","sys","tmp","asp ","aspx","cer","cfm","cgi ","pl","css","htm ","html","js","jsp","part","php","rss","xhtml","ai","bmp","gif","ico","jpeg ","jpg","max","obj","png","ps","psd","svg","tif ","tiff","3ds","3dm"}
ext_arr=["ACE","AIF","ANI","API","ARC","ARJ","ART","ASC","ASM","ASP","AVI","BAK","BAS","BAT","BFC","BIN","BIN","BMP","BUD","BZ2","C","CAB","CAT","CBL","CBT","CDA","CDT","CFML","CGI","CHM","CLASS","CLP","CMD","CMF","COM","CPL","CPP","CSS","CSV","CTY","CWK","CWS","CUR","DAO","DAT","DD","DEB","DEV","DIC","DIR","DLL","DOC","DOT","DRV","DS","DUN","DWG","DXF","EMF","EML","EPS","EPS2","EVE","EXE","FFL","FFO","FLA","FNT","FSH","GIF","GID","GRP","GZ","HEX","HLP","HT","HQX","HTM","HTML","ICL","ICM","ICO","INF","INI","JAR","JAVA","JPEG","JPG","JS","JSP","KBM","KDC","KIZ","KQP","LAB","LG","LGO","LHZ","LIT","LNK","LOG","LSP","MAQ","MAR","MDB","MDL","MFM","MHT","MID","MOD","MOV","MP3","MPEG","MPP","MSG","MSG","NCF","NDX","NFF","NFF","NITF","NLM","O","OBD","OCX","OFT","OGG","OST","PAK","PCL","PCT","PDF","PDF","PDR","PHP","PHTML","PIF","PIF","PIF","PL","PM","PM3","PM4","PM5","PM6","PNG","POL","POT","PPD","PPK","PPS","PPT","PRN","PS","PSD","PSP","PST","PUB","PWL","QBB","QBW","QIF","QXD","RAM","RAR","RAW","RDO","REG","RM","RPM","RSC","RTF","SCR","SEA","SGML","SH","SHTML","SIT","SMD","SVG","SWF","SWP","SYS","TAR","TCW","TGA","TIFF","TMP","TTF","TXT","UDF","UUE","VBS","VBX","VM","VXD","WAV","WMF","WRI","WSZ","XCF","XIF","XIF","XIF","XLS","XLT","XML","XSL","YBK","ZIP"]
lower_case_ext_arr=set({})
for i in ext_arr:
    lower_case_ext_arr.add(i.lower().strip())
s2 = lower_case_ext_arr
union = set.union(s1, s2)
print("-------------------------------")
print(union)
# print(str(len(s1))+" "+str(len(s2))+" "+str(len(union)))
